package com.woshidaniu.zxzx.dao.entities;

import java.io.Serializable;

import com.woshidaniu.common.query.ModelBase;

public class CjwtModel extends ModelBase implements Serializable{

	private static final long serialVersionUID = 6238375713235120512L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_CJWTB.WTID
     *
     * @mbggenerated
     */
    private String wtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_CJWTB.BKDM
     *
     * @mbggenerated
     */
    private String bkdm;

    private String bkmc;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_CJWTB.WTBT
     *
     * @mbggenerated
     */
    private String wtbt;
    
    private String wtnr;
    
    private String wthf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_CJWTB.SFFB
     *
     * @mbggenerated
     */
    private String sffb;
    
    private String cjsj;

    private String zxid;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_CJWTB.WTID
     *
     * @return the value of XGWEB.niutal_ZXZX_CJWTB.WTID
     *
     * @mbggenerated
     */
    public String getWtid() {
        return wtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_CJWTB.WTID
     *
     * @param wtid the value for XGWEB.niutal_ZXZX_CJWTB.WTID
     *
     * @mbggenerated
     */
    public void setWtid(String wtid) {
        this.wtid = wtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_CJWTB.BKDM
     *
     * @return the value of XGWEB.niutal_ZXZX_CJWTB.BKDM
     *
     * @mbggenerated
     */
    public String getBkdm() {
        return bkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_CJWTB.BKDM
     *
     * @param bkdm the value for XGWEB.niutal_ZXZX_CJWTB.BKDM
     *
     * @mbggenerated
     */
    public void setBkdm(String bkdm) {
        this.bkdm = bkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_CJWTB.WTBT
     *
     * @return the value of XGWEB.niutal_ZXZX_CJWTB.WTBT
     *
     * @mbggenerated
     */
    public String getWtbt() {
        return wtbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_CJWTB.WTBT
     *
     * @param wtbt the value for XGWEB.niutal_ZXZX_CJWTB.WTBT
     *
     * @mbggenerated
     */
    public void setWtbt(String wtbt) {
        this.wtbt = wtbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_CJWTB.SFFB
     *
     * @return the value of XGWEB.niutal_ZXZX_CJWTB.SFFB
     *
     * @mbggenerated
     */
    public String getSffb() {
        return sffb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_CJWTB.SFFB
     *
     * @param sffb the value for XGWEB.niutal_ZXZX_CJWTB.SFFB
     *
     * @mbggenerated
     */
    public void setSffb(String sffb) {
        this.sffb = sffb;
    }

	public String getWtnr() {
		return wtnr;
	}

	public void setWtnr(String wtnr) {
		this.wtnr = wtnr;
	}

	public String getWthf() {
		return wthf;
	}

	public void setWthf(String wthf) {
		this.wthf = wthf;
	}

	public String getCjsj() {
		return cjsj;
	}

	public void setCjsj(String cjsj) {
		this.cjsj = cjsj;
	}

	public String getBkmc() {
		return bkmc;
	}

	public void setBkmc(String bkmc) {
		this.bkmc = bkmc;
	}

	public String getZxid() {
		return zxid;
	}

	public void setZxid(String zxid) {
		this.zxid = zxid;
	}
    
}