package com.woshidaniu.zxzx.dao.entities;

import java.io.Serializable;

public class CsszModel implements Serializable{

	private static final long serialVersionUID = 3724706579144230595L;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_CSSZB.CSDM
     *
     * @mbggenerated
     */
    private String csdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_CSSZB.CSMC
     *
     * @mbggenerated
     */
    private String csmc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_CSSZB.CSDM
     *
     * @return the value of XGWEB.niutal_ZXZX_CSSZB.CSDM
     *
     * @mbggenerated
     */
    public String getCsdm() {
        return csdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_CSSZB.CSDM
     *
     * @param csdm the value for XGWEB.niutal_ZXZX_CSSZB.CSDM
     *
     * @mbggenerated
     */
    public void setCsdm(String csdm) {
        this.csdm = csdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_CSSZB.CSMC
     *
     * @return the value of XGWEB.niutal_ZXZX_CSSZB.CSMC
     *
     * @mbggenerated
     */
    public String getCsmc() {
        return csmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_CSSZB.CSMC
     *
     * @param csmc the value for XGWEB.niutal_ZXZX_CSSZB.CSMC
     *
     * @mbggenerated
     */
    public void setCsmc(String csmc) {
        this.csmc = csmc;
    }

	public CsszModel(String csdm, String csmc) {
		super();
		this.csdm = csdm;
		this.csmc = csmc;
	}

	public CsszModel() {
		super();
	}
	
	private String kg;
	
	private String kssj;
	
	private String jssj;
	
	private String zxms;
	
	private String dlms;
	
	private String loginUrl;
	
	private String authUrl;
	
	private String rmzxjsfs;
	
	private String rmzxjssjd;
	
	private String rmzxxsts;
	
	private String lxr;
	
	private String dh;
	
	private String dzyx;
	
	private String dz;
	
	/**
	 * 是否显示我的问题栏目
	 */
	private String sfxswdwt;
	/**
	 * 是否显示我要提问
	 */
	private String sfxswytw;
	/**
	 * 是否允许未登录查询问题
	 */
	private String sfyxwdlcxwt;
	

	public String getKg() {
		return kg;
	}

	public void setKg(String kg) {
		this.kg = kg;
	}

	public String getKssj() {
		return kssj;
	}

	public void setKssj(String kssj) {
		this.kssj = kssj;
	}

	public String getJssj() {
		return jssj;
	}

	public void setJssj(String jssj) {
		this.jssj = jssj;
	}

	public String getZxms() {
		return zxms;
	}

	public void setZxms(String zxms) {
		this.zxms = zxms;
	}

	public String getRmzxjsfs() {
		return rmzxjsfs;
	}

	public void setRmzxjsfs(String rmzxjsfs) {
		this.rmzxjsfs = rmzxjsfs;
	}

	public String getRmzxjssjd() {
		return rmzxjssjd;
	}

	public void setRmzxjssjd(String rmzxjssjd) {
		this.rmzxjssjd = rmzxjssjd;
	}

	public String getRmzxxsts() {
		return rmzxxsts;
	}

	public void setRmzxxsts(String rmzxxsts) {
		this.rmzxxsts = rmzxxsts;
	}

	public String getLxr() {
		return lxr;
	}

	public void setLxr(String lxr) {
		this.lxr = lxr;
	}

	public String getDh() {
		return dh;
	}

	public void setDh(String dh) {
		this.dh = dh;
	}

	public String getDzyx() {
		return dzyx;
	}

	public void setDzyx(String dzyx) {
		this.dzyx = dzyx;
	}

	public String getDz() {
		return dz;
	}

	public void setDz(String dz) {
		this.dz = dz;
	}

	public String getDlms() {
		return dlms;
	}

	public void setDlms(String dlms) {
		this.dlms = dlms;
	}

	public String getLoginUrl() {
		return loginUrl;
	}

	public void setLoginUrl(String loginUrl) {
		this.loginUrl = loginUrl;
	}

	public String getAuthUrl() {
		return authUrl;
	}

	public void setAuthUrl(String authUrl) {
		this.authUrl = authUrl;
	}

	public String getSfxswdwt() {
		return sfxswdwt;
	}

	public void setSfxswdwt(String sfxswdwt) {
		this.sfxswdwt = sfxswdwt;
	}

	public String getSfxswytw() {
		return sfxswytw;
	}

	public void setSfxswytw(String sfxswytw) {
		this.sfxswytw = sfxswytw;
	}

	public String getSfyxwdlcxwt() {
		return sfyxwdlcxwt;
	}

	public void setSfyxwdlcxwt(String sfyxwdlcxwt) {
		this.sfyxwdlcxwt = sfyxwdlcxwt;
	}
	
}