package com.woshidaniu.zxzx.dao.entities;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.woshidaniu.common.query.ModelBase;

public class kzdkModel extends ModelBase implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5724007212670278507L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_BKXXB.BKDM
     *
     * @mbggenerated
     */
    private String bkdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_BKXXB.BKMC
     *
     * @mbggenerated
     */
    private String bkmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_BKXXB.SFQY
     *
     * @mbggenerated
     */
    private String sfqy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_BKXXB.XSXS
     *
     * @mbggenerated
     */
    private String xsxs;

    private Integer zxwtCount;
    
    private List<ZxwtModel> zxwtModelList;
    
    private List<String> webkzdkdmList;
    
    private Map<String,String> postData = new HashMap<String, String>();
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_BKXXB.BKDM
     *
     * @return the value of XGWEB.niutal_ZXZX_BKXXB.BKDM
     *
     * @mbggenerated
     */
    public String getBkdm() {
        return bkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_BKXXB.BKDM
     *
     * @param bkdm the value for XGWEB.niutal_ZXZX_BKXXB.BKDM
     *
     * @mbggenerated
     */
    public void setBkdm(String bkdm) {
        this.bkdm = bkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_BKXXB.BKMC
     *
     * @return the value of XGWEB.niutal_ZXZX_BKXXB.BKMC
     *
     * @mbggenerated
     */
    public String getBkmc() {
        return bkmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_BKXXB.BKMC
     *
     * @param bkmc the value for XGWEB.niutal_ZXZX_BKXXB.BKMC
     *
     * @mbggenerated
     */
    public void setBkmc(String bkmc) {
        this.bkmc = bkmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_BKXXB.SFQY
     *
     * @return the value of XGWEB.niutal_ZXZX_BKXXB.SFQY
     *
     * @mbggenerated
     */
    public String getSfqy() {
        return sfqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_BKXXB.SFQY
     *
     * @param sfqy the value for XGWEB.niutal_ZXZX_BKXXB.SFQY
     *
     * @mbggenerated
     */
    public void setSfqy(String sfqy) {
        this.sfqy = sfqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_BKXXB.XSXS
     *
     * @return the value of XGWEB.niutal_ZXZX_BKXXB.XSXS
     *
     * @mbggenerated
     */
    public String getXsxs() {
        return xsxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_BKXXB.XSXS
     *
     * @param xsxs the value for XGWEB.niutal_ZXZX_BKXXB.XSXS
     *
     * @mbggenerated
     */
    public void setXsxs(String xsxs) {
        this.xsxs = xsxs;
    }

	public List<ZxwtModel> getZxwtModelList() {
		return zxwtModelList;
	}

	public void setZxwtModelList(List<ZxwtModel> zxwtModelList) {
		this.zxwtModelList = zxwtModelList;
	}

	public Integer getZxwtCount() {
		return zxwtCount;
	}

	public void setZxwtCount(Integer zxwtCount) {
		this.zxwtCount = zxwtCount;
	}

	public List<String> getWebkzdkdmList() {
		return webkzdkdmList;
	}

	public void setWebkzdkdmList(List<String> webkzdkdmList) {
		this.webkzdkdmList = webkzdkdmList;
	}

	public Map<String, String> getPostData() {
		return postData;
	}

	public void setPostData(Map<String, String> postData) {
		this.postData = postData;
	}
    
    
}