/**
 * 我是大牛软件股份有限公司
 */
package com.woshidaniu.zxzx.dao.entities;

import java.io.Serializable;

import com.woshidaniu.common.query.ModelBase;
import com.woshidaniu.search.core.SearchModel;

/**
 * @类名 YhbkModel.java
 * @工号 [1036]
 * @姓名 xiaokang
 * @创建时间 2016 2016年5月23日 下午4:32:08
 * @功能描述 用户咨询板块
 * 
 */
public class YhbkModel extends ModelBase implements Serializable{

	private static final long serialVersionUID = -77064535668535396L;
	
	private SearchModel searchModel;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column niutal_ZXZX_BKYHB.BKDM
     *
     * @mbggenerated
     */
    private String bkdm;
    
    
    private String bkmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column niutal_ZXZX_BKYHB.ZGH
     *
     * @mbggenerated
     */
    private String zgh;
    
    private String xm;
    
    private String jgdm;

    /**
     * 用户数
     */
    private String yhs;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column niutal_ZXZX_BKYHB.BKDM
     *
     * @return the value of niutal_ZXZX_BKYHB.BKDM
     *
     * @mbggenerated
     */
    public String getBkdm() {
        return bkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_BKYHB.BKDM
     *
     * @param bkdm the value for XGWEB.niutal_ZXZX_BKYHB.BKDM
     *
     * @mbggenerated
     */
    public void setBkdm(String bkdm) {
        this.bkdm = bkdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_BKYHB.ZGH
     *
     * @return the value of XGWEB.niutal_ZXZX_BKYHB.ZGH
     *
     * @mbggenerated
     */
    public String getZgh() {
        return zgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_BKYHB.ZGH
     *
     * @param zgh the value for XGWEB.niutal_ZXZX_BKYHB.ZGH
     *
     * @mbggenerated
     */
    public void setZgh(String zgh) {
        this.zgh = zgh;
    }

	public String getYhs() {
		return yhs;
	}

	public void setYhs(String yhs) {
		this.yhs = yhs;
	}

	public String getBkmc() {
		return bkmc;
	}

	public void setBkmc(String bkmc) {
		this.bkmc = bkmc;
	}

	public String getXm() {
		return xm;
	}

	public void setXm(String xm) {
		this.xm = xm;
	}

	public String getJgdm() {
		return jgdm;
	}

	public void setJgdm(String jgdm) {
		this.jgdm = jgdm;
	}

	public SearchModel getSearchModel() {
		return searchModel;
	}

	public void setSearchModel(SearchModel searchModel) {
		this.searchModel = searchModel;
	}

}
