package com.woshidaniu.zxzx.dao.entities;

import java.io.Serializable;

public class ZxhfModel implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8694336910898284317L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXHFB.HFID
     *
     * @mbggenerated
     */
    private String hfid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXHFB.ZXID
     *
     * @mbggenerated
     */
    private String zxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXHFB.HFR
     *
     * @mbggenerated
     */
    private String hfr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXHFB.HFSJ
     *
     * @mbggenerated
     */
    private String hfsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXHFB.HFNR
     *
     * @mbggenerated
     */
    private String hfnr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_ZXHFB.HFID
     *
     * @return the value of XGWEB.niutal_ZXZX_ZXHFB.HFID
     *
     * @mbggenerated
     */
    public String getHfid() {
        return hfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_ZXHFB.HFID
     *
     * @param hfid the value for XGWEB.niutal_ZXZX_ZXHFB.HFID
     *
     * @mbggenerated
     */
    public void setHfid(String hfid) {
        this.hfid = hfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_ZXHFB.ZXID
     *
     * @return the value of XGWEB.niutal_ZXZX_ZXHFB.ZXID
     *
     * @mbggenerated
     */
    public String getZxid() {
        return zxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_ZXHFB.ZXID
     *
     * @param zxid the value for XGWEB.niutal_ZXZX_ZXHFB.ZXID
     *
     * @mbggenerated
     */
    public void setZxid(String zxid) {
        this.zxid = zxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_ZXHFB.HFR
     *
     * @return the value of XGWEB.niutal_ZXZX_ZXHFB.HFR
     *
     * @mbggenerated
     */
    public String getHfr() {
        return hfr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_ZXHFB.HFR
     *
     * @param hfr the value for XGWEB.niutal_ZXZX_ZXHFB.HFR
     *
     * @mbggenerated
     */
    public void setHfr(String hfr) {
        this.hfr = hfr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_ZXHFB.HFSJ
     *
     * @return the value of XGWEB.niutal_ZXZX_ZXHFB.HFSJ
     *
     * @mbggenerated
     */
    public String getHfsj() {
        return hfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_ZXHFB.HFSJ
     *
     * @param hfsj the value for XGWEB.niutal_ZXZX_ZXHFB.HFSJ
     *
     * @mbggenerated
     */
    public void setHfsj(String hfsj) {
        this.hfsj = hfsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_ZXZX_ZXHFB.HFNR
     *
     * @return the value of XGWEB.niutal_ZXZX_ZXHFB.HFNR
     *
     * @mbggenerated
     */
    public String getHfnr() {
        return hfnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_ZXZX_ZXHFB.HFNR
     *
     * @param hfnr the value for XGWEB.niutal_ZXZX_ZXHFB.HFNR
     *
     * @mbggenerated
     */
    public void setHfnr(String hfnr) {
        this.hfnr = hfnr;
    }
}