package com.woshidaniu.zxzx.dao.entities;

import java.io.Serializable;
import java.util.List;

import com.woshidaniu.common.query.ModelBase;
import com.woshidaniu.search.core.SearchModel;

public class ZxwtModel extends ModelBase implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 5982225478925511970L;

	/**
	 * 
	 */
	private SearchModel searchModel;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXWTB.ZXID
     *
     * @mbggenerated
     */
    private String zxid;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXWTB.BKDM
     *
     * @mbggenerated
     */
    private String bkdm;
    
    private List<String> bkdms;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXWTB.kzdT
     *
     * @mbggenerated
     */
    private String kzdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXWTB.ZXSJ
     *
     * @mbggenerated
     */
    private String zxsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXWTB.ZXR
     *
     * @mbggenerated
     */
    private String zxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXWTB.SFGK
     *
     * @mbggenerated
     */
    private String sfgk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXWTB.DJL
     *
     * @mbggenerated
     */
    private Integer djl;
    
    /**
     * 是否匿名,默认不是匿名
     */
    private String sfnm = "0"; 
    
    /**
     * 是否设置为常见问题
     */
    private String cjwt;
    
    /**
     * 当前登录用户
     */
    private String loginUser;
    /**
     * 搜索字段
     */
    private String webSearch;
    
    /**
     * 搜索字段
     */
    private List<kzdkModel> webSearchBkdmList;
    
    /**
     * 是否需要同时删除常见问题表信息
     */
    private String delCjwt;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_ZXZX_ZXWTB.ZXNR
     *
     * @mbggenerated
     */
    private String zxnr;

    private String hfzt;
    
    private String conditionSql = "";
    
    private kzdkModel kzdkModel;
    
    private ZxhfModel zxhfModel;
    
    private ZxrModel zxrModel = new ZxrModel();
    
    public String getZxid() {
        return zxid;
    }

    public void setZxid(String zxid) {
        this.zxid = zxid;
    }

    public String getkzdt() {
        return kzdt;
    }

    public void setkzdt(String kzdt) {
        this.kzdt = kzdt;
    }

    public String getZxsj() {
        return zxsj;
    }

    public void setZxsj(String zxsj) {
        this.zxsj = zxsj;
    }

    public String getZxr() {
        return zxr;
    }

    public void setZxr(String zxr) {
        this.zxr = zxr;
    }

    public String getSfgk() {
        return sfgk;
    }

    public void setSfgk(String sfgk) {
        this.sfgk = sfgk;
    }

    public Integer getDjl() {
        return djl;
    }

    public void setDjl(Integer djl) {
        this.djl = djl;
    }

    public String getZxnr() {
        return zxnr;
    }

    public void setZxnr(String zxnr) {
        this.zxnr = zxnr;
    }

	public String getBkdm() {
		return bkdm;
	}

	public void setBkdm(String bkdm) {
		this.bkdm = bkdm;
	}

	public kzdkModel getkzdkModel() {
		return kzdkModel;
	}

	public void setkzdkModel(kzdkModel kzdkModel) {
		this.kzdkModel = kzdkModel;
	}

	public ZxrModel getZxrModel() {
		return zxrModel;
	}

	public void setZxrModel(ZxrModel zxrModel) {
		this.zxrModel = zxrModel;
	}

	public ZxhfModel getZxhfModel() {
		return zxhfModel;
	}

	public void setZxhfModel(ZxhfModel zxhfModel) {
		this.zxhfModel = zxhfModel;
	}

	public String getHfzt() {
		return hfzt;
	}

	public void setHfzt(String hfzt) {
		this.hfzt = hfzt;
	}

	public SearchModel getSearchModel() {
		return searchModel;
	}

	public void setSearchModel(SearchModel searchModel) {
		this.searchModel = searchModel;
	}

	public String getWebSearch() {
		return webSearch;
	}

	public void setWebSearch(String webSearch) {
		this.webSearch = webSearch;
	}

	public List<kzdkModel> getWebSearchBkdmList() {
		return webSearchBkdmList;
	}

	public void setWebSearchBkdmList(List<kzdkModel> webSearchBkdmList) {
		this.webSearchBkdmList = webSearchBkdmList;
	}

	public String getLoginUser() {
		return loginUser;
	}

	public void setLoginUser(String loginUser) {
		this.loginUser = loginUser;
	}

	public String getCjwt() {
		return cjwt;
	}

	public void setCjwt(String cjwt) {
		this.cjwt = cjwt;
	}

	public String getDelCjwt() {
		return delCjwt;
	}

	public void setDelCjwt(String delCjwt) {
		this.delCjwt = delCjwt;
	}

	
	
	private String yzm;
	
	private String webSearchBkdmValue;
	
	private List<String> webSearchBkdmValues;
	
	private String webSearchValue;

	public String getYzm() {
		return yzm;
	}

	public void setYzm(String yzm) {
		this.yzm = yzm;
	}

	public String getWebSearchBkdmValue() {
		return webSearchBkdmValue;
	}

	public void setWebSearchBkdmValue(String webSearchBkdmValue) {
		this.webSearchBkdmValue = webSearchBkdmValue;
	}

	public String getWebSearchValue() {
		return webSearchValue;
	}

	public void setWebSearchValue(String webSearchValue) {
		this.webSearchValue = webSearchValue;
	}

	public String getSfnm() {
		return sfnm;
	}

	public void setSfnm(String sfnm) {
		this.sfnm = sfnm;
	}

	public List<String> getWebSearchBkdmValues() {
		return webSearchBkdmValues;
	}

	public void setWebSearchBkdmValues(List<String> webSearchBkdmValues) {
		this.webSearchBkdmValues = webSearchBkdmValues;
	}

	public List<String> getBkdms() {
		return bkdms;
	}

	public void setBkdms(List<String> bkdms) {
		this.bkdms = bkdms;
	}

	public String getConditionSql() {
		return conditionSql;
	}

	public void setConditionSql(String conditionSql) {
		this.conditionSql = conditionSql;
	}
}