/**---------------niutal_DATA_RULE表---------------start**/
CREATE TABLE "niutal_DATA_RULE" (
"RULE_ID" NVARCHAR2(32) DEFAULT SYS_GUID()  NOT NULL ,
"GROUP_ID" NVARCHAR2(32) NOT NULL ,
"METHOD_REGEXS" NVARCHAR2(2000) NULL ,
"PREPOSITION_SQL" NVARCHAR2(1000) NULL ,
"POSTPOSITION_SQL" NVARCHAR2(1000) NULL ,
"REPLACE_REGEXS" NVARCHAR2(2000) NULL ,
"REPLACE_SQLS" NVARCHAR2(2000) NULL 
);

COMMENT ON TABLE "niutal_DATA_RULE" IS '数据权限规则表';
COMMENT ON COLUMN "niutal_DATA_RULE"."GROUP_ID" IS '关联组';
COMMENT ON COLUMN "niutal_DATA_RULE"."METHOD_REGEXS" IS '被拦截的方法';
COMMENT ON COLUMN "niutal_DATA_RULE"."PREPOSITION_SQL" IS '前置SQL';
COMMENT ON COLUMN "niutal_DATA_RULE"."POSTPOSITION_SQL" IS '后置SQL';
COMMENT ON COLUMN "niutal_DATA_RULE"."REPLACE_REGEXS" IS '被替换SQL正则表达式';
COMMENT ON COLUMN "niutal_DATA_RULE"."REPLACE_SQLS" IS '替换的SQL';


ALTER TABLE "niutal_DATA_RULE" ADD CONSTRAINT KEY_niutal_DATA_RULE_ID PRIMARY KEY ("RULE_ID");

/**---------------niutal_DATA_RULE表---------------end**/


/**---------------niutal_DATA_RULE_GROUP表---------------start**/
CREATE TABLE "niutal_DATA_RULE_GROUP" (
"GROUP_ID" NVARCHAR2(32) DEFAULT SYS_GUID()  NOT NULL ,
"GROUP_CODE" NVARCHAR2(100) NULL ,
"GROUP_NAME" NVARCHAR2(200) NULL ,
"GROUP_TYPE" NVARCHAR2(100) NULL ,
"SELECT_ITEM" NVARCHAR2(1000) NULL 
);

COMMENT ON TABLE "niutal_DATA_RULE_GROUP" IS '数据权限规则组';
COMMENT ON COLUMN "niutal_DATA_RULE_GROUP"."GROUP_CODE" IS '规则组代码';
COMMENT ON COLUMN "niutal_DATA_RULE_GROUP"."GROUP_NAME" IS '规则组名称';
COMMENT ON COLUMN "niutal_DATA_RULE_GROUP"."GROUP_TYPE" IS '规则组类型';
COMMENT ON COLUMN "niutal_DATA_RULE_GROUP"."SELECT_ITEM" IS '包含的选项(sql)';

ALTER TABLE "niutal_DATA_RULE_GROUP" ADD CONSTRAINT KEY_RULE_GROUP_ID PRIMARY KEY ("GROUP_ID");

/**---------------niutal_DATA_RULE_GROUP表---------------end**/


/**---------------niutal_DATA_RULE_GROUP_USER表---------------start**/
CREATE TABLE "niutal_DATA_RULE_GROUP_USER" (
"GROUP_ID" NVARCHAR2(32) NOT NULL ,
"YHM" NVARCHAR2(50) NOT NULL ,
"ITEM_VALUES" NVARCHAR2(2000) NULL 
)
;
COMMENT ON TABLE "niutal_DATA_RULE_GROUP_USER" IS '数据权限组与用户的关系';
COMMENT ON COLUMN "niutal_DATA_RULE_GROUP_USER"."ITEM_VALUES" IS '选项值';

/**---------------niutal_DATA_RULE_GROUP_USER表---------------end**/

/**---------------niutal_DATA_RULE_GROUP_ROLE表---------------start**/
CREATE TABLE "niutal_DATA_RULE_GROUP_ROLE" (
"GROUP_ID" NVARCHAR2(32) NOT NULL ,
"JSDM" NVARCHAR2(50) NOT NULL ,
"ITEM_VALUES" NVARCHAR2(2000) NULL 
);

COMMENT ON TABLE "niutal_DATA_RULE_GROUP_ROLE" IS '数据权限组与角色的关系';
COMMENT ON COLUMN "niutal_DATA_RULE_GROUP_ROLE"."ITEM_VALUES" IS '选项值';

/**---------------niutal_DATA_RULE_GROUP_ROLE表---------------end**/


/**---------------表结构变更---------------start**/

/**权限与用户关系中增加角色代码*/
DELETE FROM niutal_DATA_RULE_GROUP_USER;
ALTER TABLE "niutal_DATA_RULE_GROUP_USER" ADD(
	"JSDM" NVARCHAR2(50) NOT NULL
);
COMMENT ON COLUMN "niutal_DATA_RULE_GROUP_USER"."JSDM" IS '角色代码';

/**规则设计增加启用状态**/
ALTER TABLE "niutal_DATA_RULE" ADD(
	"RULE_ENABLE" CHAR(1) NULL
);
COMMENT ON COLUMN "niutal_DATA_RULE"."RULE_ENABLE" IS '是否启用';

UPDATE niutal_DATA_RULE SET RULE_ENABLE = '1';




/**---------------表结构变更---------------end**/