package com.woshidaniu.licenseManagement.dao.entities;

import java.io.Serializable;

import com.woshidaniu.common.query.ModelBase;


/**
 * 
 * <p>
 *   <h3>niutal框架<h3>
 *   说明：License Model
 * <p>
 * @author <a href="#">xiaokang[1036]<a>
 * @version 2016年6月23日下午3:19:16
 */
public class LicenseModel  extends ModelBase implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -6771279990484698858L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_LICENSE.AUTH_ID
     *
     * @mbggenerated
     */
    private String authId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_LICENSE.AUTH_USER
     *
     * @mbggenerateds
     */
    private String authUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_LICENSE.AUTH_USER_CODE
     *
     * @mbggenerated
     */
    private String authUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_LICENSE.AUTH_DATE
     *
     * @mbggenerated
     */
    private String authDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_LICENSE.START_DATE
     *
     * @mbggenerated
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_LICENSE.EXPIRE_DATE
     *
     * @mbggenerated
     */
    private String expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_LICENSE.USAGE
     *
     * @mbggenerated
     */
    private String usage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_LICENSE.USAGE_COUNT
     *
     * @mbggenerated
     */
    private String usageCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_LICENSE.ALERT
     *
     * @mbggenerated
     */
    private String alert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XGWEB.niutal_LICENSE.BZXX
     *
     * @mbggenerated
     */
    private String bzxx;
    
    /**
     * 
     */
    private String logDate;

    /**
     * 创建人
     */
    private String createUser;
    
    /**
     * 开发模式
     */
    private String devMode;
    
    /**
     * 业务系统名称
     */
    private String productName;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_LICENSE.AUTH_ID
     *
     * @return the value of XGWEB.niutal_LICENSE.AUTH_ID
     *
     * @mbggenerated
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_LICENSE.AUTH_ID
     *
     * @param authId the value for XGWEB.niutal_LICENSE.AUTH_ID
     *
     * @mbggenerated
     */
    public void setAuthId(String authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_LICENSE.AUTH_USER
     *
     * @return the value of XGWEB.niutal_LICENSE.AUTH_USER
     *
     * @mbggenerated
     */
    public String getAuthUser() {
        return authUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_LICENSE.AUTH_USER
     *
     * @param authUser the value for XGWEB.niutal_LICENSE.AUTH_USER
     *
     * @mbggenerated
     */
    public void setAuthUser(String authUser) {
        this.authUser = authUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_LICENSE.AUTH_USER_CODE
     *
     * @return the value of XGWEB.niutal_LICENSE.AUTH_USER_CODE
     *
     * @mbggenerated
     */
    public String getAuthUserCode() {
        return authUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_LICENSE.AUTH_USER_CODE
     *
     * @param authUserCode the value for XGWEB.niutal_LICENSE.AUTH_USER_CODE
     *
     * @mbggenerated
     */
    public void setAuthUserCode(String authUserCode) {
        this.authUserCode = authUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_LICENSE.AUTH_DATE
     *
     * @return the value of XGWEB.niutal_LICENSE.AUTH_DATE
     *
     * @mbggenerated
     */
    public String getAuthDate() {
        return authDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_LICENSE.AUTH_DATE
     *
     * @param authDate the value for XGWEB.niutal_LICENSE.AUTH_DATE
     *
     * @mbggenerated
     */
    public void setAuthDate(String authDate) {
        this.authDate = authDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_LICENSE.START_DATE
     *
     * @return the value of XGWEB.niutal_LICENSE.START_DATE
     *
     * @mbggenerated
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_LICENSE.START_DATE
     *
     * @param startDate the value for XGWEB.niutal_LICENSE.START_DATE
     *
     * @mbggenerated
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_LICENSE.EXPIRE_DATE
     *
     * @return the value of XGWEB.niutal_LICENSE.EXPIRE_DATE
     *
     * @mbggenerated
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_LICENSE.EXPIRE_DATE
     *
     * @param expireDate the value for XGWEB.niutal_LICENSE.EXPIRE_DATE
     *
     * @mbggenerated
     */
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_LICENSE.USAGE
     *
     * @return the value of XGWEB.niutal_LICENSE.USAGE
     *
     * @mbggenerated
     */
    public String getUsage() {
        return usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_LICENSE.USAGE
     *
     * @param usage the value for XGWEB.niutal_LICENSE.USAGE
     *
     * @mbggenerated
     */
    public void setUsage(String usage) {
        this.usage = usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_LICENSE.USAGE_COUNT
     *
     * @return the value of XGWEB.niutal_LICENSE.USAGE_COUNT
     *
     * @mbggenerated
     */
    public String getUsageCount() {
        return usageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_LICENSE.USAGE_COUNT
     *
     * @param usageCount the value for XGWEB.niutal_LICENSE.USAGE_COUNT
     *
     * @mbggenerated
     */
    public void setUsageCount(String usageCount) {
        this.usageCount = usageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_LICENSE.ALERT
     *
     * @return the value of XGWEB.niutal_LICENSE.ALERT
     *
     * @mbggenerated
     */
    public String getAlert() {
        return alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_LICENSE.ALERT
     *
     * @param alert the value for XGWEB.niutal_LICENSE.ALERT
     *
     * @mbggenerated
     */
    public void setAlert(String alert) {
        this.alert = alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XGWEB.niutal_LICENSE.BZXX
     *
     * @return the value of XGWEB.niutal_LICENSE.BZXX
     *
     * @mbggenerated
     */
    public String getBzxx() {
        return bzxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XGWEB.niutal_LICENSE.BZXX
     *
     * @param bzxx the value for XGWEB.niutal_LICENSE.BZXX
     *
     * @mbggenerated
     */
    public void setBzxx(String bzxx) {
        this.bzxx = bzxx;
    }

	public String getLogDate() {
		return logDate;
	}

	public void setLogDate(String logDate) {
		this.logDate = logDate;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getDevMode() {
		return devMode;
	}

	public void setDevMode(String devMode) {
		this.devMode = devMode;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}
    
}